---
- name: install haproxy and socat
  apt: pkg={{ item }} state=latest
  with_items:
  - haproxy
  - socat

- name: enable haproxy
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify: restart haproxy

- name: deploy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: create backend stats script
  shell: >
    echo 'echo "show stat" | sudo nc -U /var/lib/haproxy/stats | cut -d"," -f 1,18 | grep ln-app' \
    > /usr/local/bin/haproxy_stats.sh && chmod +x /usr/local/bin/haproxy_stats.sh
