---
- name: LN-inf-2.0
  hosts: all
  tasks:
    - name: Load env vars
      include_vars: env_vars/base.yml
    - name: Collect DB Master IP for dev
      set_fact: redismaster_ip="{{ hostvars["redis-master"].ansible_eth1.ipv4.address}}"
      when: not prod
    - name: Collect DB Master IP for prod
      set_fact: redismaster_ip="{{ hostvars["redis-master-prod"].ansible_eth1.ipv4.address}}"
      when: prod

- name: LN-inf-app
  hosts: app
  user: root
  # sudo: yes
  roles:
    - docker
    - app
