---
- name: LN-inf-2.0
  hosts: all
  tasks:
    - name: Load env vars
      include_vars: env_vars/base.yml
    - name: Collect DB Master IP
      set_fact: redismaster_ip="{{ hostvars["redis-master"].ansible_eth1.ipv4.address}}"

- name: LN-inf-redis
  hosts: redis1
  user: vagrant
  sudo: yes
  roles:
    - redis

- name: LN-inf-app
  hosts: app
  user: root
  # sudo: yes
  roles:
    - docker
    - app

# - name: LN-inf-dockerbuilder
#   hosts: localhost
#   roles:
#     - app-docker-builder
