---
- name: LN-inf-2.0
  hosts: all
  user: root
  tasks:
    - name: Load env vars
      include_vars: env_vars/base.yml
    - name: Collect DB Master IP for dev
      set_fact: redismaster_ip="{{ hostvars["redis-master"].ansible_eth1.ipv4.address}}"
      when: prod is not defined
    - name: Collect DB Master IP for prod
      set_fact: redismaster_ip="{{ hostvars["lb1p"].ansible_eth1.ipv4.address}}"
      when: prod is defined

- name: LN-inf-redis
  hosts: redis-master-prod
  user: root
  roles:
    - redis

- name: LN-inf-app
  hosts: app
  user: root
  roles:
    - docker
    - app

- name: LN-inf-lb
  hosts: lb
  user: root
  roles:
    - lb
