---
- name: LN-inf-redis-master
  hosts: redis-master-prod
  user: root
  roles:
    - redis

- name: LN-inf-redis-slave
  hosts: redis-slave-prod
  user: root

  vars:
    - redis_slaveof: '{{ hostvars["redis-master"].ansible_eth1.ipv4.address}} 6379'
  roles:
    - redis
