
---

- name: LN-inf-2.0
  hosts: all
  tasks:
    - name: Load env vars
      include_vars: env_vars/base.yml
    - debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]["ansible_fqdn"] }} {{ hostvars[inventory_hostname]["ansible_hostname"] }}"
    - name: Collect DB Master IP
      set_fact: redismaster_ip="{{ hostvars["redis-master"].ansible_default_ipv4.address}}"


- name: Create a {{ application_name }} Redis virtual machine via vagrant
  hosts: redis
  sudo: yes
  sudo_user: root
  remote_user: vagrant

  vars_files:
    - env_vars/base.yml
    # todo
    #- env_vars/vagrant.yml

  roles:
    - redis

- name: Create a {{ application_name }} app virtual machine via vagrant
  hosts: app1
  sudo: yes
  sudo_user: root
  remote_user: vagrant

  vars_files:
    - env_vars/base.yml

  roles:
    - docker
    - app
